# Generated by Django 2.2 on 2019-11-04 11:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191104_0951'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
                ('obejects', django.db.models.manager.Manager()),
            ],
        ),
    ]
